version: '3'
services:

  jenkins:
    image: jenkinsci/blueocean
    user: root
    environment: 
      JENKINS_DATA: ${PWD}/jenkins-data
    volumes: 
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8038:8080
    restart: unless-stopped
